import { Template } from '../types/types.ts';

const templates: Template[] = [
  {
    key: 'taskSingle',
    emojiKey: 'clipboard',
    titleGroup: 'Ops',
    title: 'Single Task Request',
    channelTip: 'Select related *site channel*',
    isSlackDeprecated: false,
    isEnabled: true,
  },
  {
    key: 'taskBulk',
    emojiKey: 'clipboard',
    titleGroup: 'Ops',
    title: 'Bulk Tasks Request',
    channelTip: 'Select related *site channel*',
    isSlackDeprecated: false,
    isEnabled: true,
  },
  {
    key: 'signage',
    emojiKey: 'placard',
    titleGroup: 'Ops',
    title: 'Signage Request',
    channelTip: 'Select *#ba_signage_labels* as the channel',
    isSlackDeprecated: false,
    isEnabled: true,
  },
  {
    key: 'equipment',
    emojiKey: 'wrench',
    titleGroup: 'Ops',
    title: 'Equipment Issue',
    channelTip: 'Select related *site channel*',
    isSlackDeprecated: false,
    isEnabled: true,
  },
  {
    key: 'qcStarting',
    emojiKey: 'straight_ruler',
    titleGroup: 'Flex',
    title: 'QC Starting',
    channelTip: 'Select * site channel* of QC Check',
    isSlackDeprecated: false,
    isEnabled: true,
  },
  {
    key: 'qcRemarks',
    emojiKey: 'black_nib',
    titleGroup: 'Flex',
    title: 'QC Remarks',
    channelTip: 'Select * site channel* of QC Check',
    isSlackDeprecated: false,
    isEnabled: true,
  },
  {
    key: 'trainee',
    emojiKey: 'mortar_board',
    titleGroup: 'Flex',
    title: 'Trainee Recap',
    channelTip: 'Select *#ba_flex_operators* as the channel',
    isSlackDeprecated: false,
    isEnabled: true,
  },
  {
    key: 'order',
    emojiKey: 'package',
    titleGroup: 'CAF',
    title: 'Order Report',
    channelTip: 'Select *DM to yourself* for copy-paste use',
    isSlackDeprecated: true,
    isEnabled: true,
  },
  {
    key: 'dro',
    emojiKey: 'calendar',
    titleGroup: 'CAF',
    title: 'DRO Report',
    channelTip: 'Select *DM to yourself* for copy-paste use',
    isSlackDeprecated: true,
    isEnabled: true,
  },
];

export default templates;
